# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# Build config
# https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba
build:
  os: "ubuntu-20.04"
  tools:
    python: mambaforge

# Sphinx config
sphinx:
  builder: html
  configuration: docs/conf.py

# Environment config
conda:
  environment: docs/environment.yml
