# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# Build config
# https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba
build:
  os: "ubuntu-20.04"
  image: latest
  tools:
    python: "mambaforge-4.10"

# Sphinx config
sphinx:
  builder: html
  configuration: docs/conf.py

# Python config
python:
  version: 3.6
  system_packages: true

# Environment config
conda:
  environment: docs/environment.yml
